name: CI

on:
  push:
    branches:
      - '**'

jobs:
  run-lint:
    uses: kornsupadej/pest-control-factory/.github/workflows/lint.yaml@master
  run-test:
    uses: kornsupadej/pest-control-factory/.github/workflows/test.yaml@master